### ISSUE TITLE
GuiDevelopmentException: Property 'isColumnRequired' is not found in entity 'ddcdi$ImportAttributeMapper'

### ISSUE THREAD

**Issue by sebastianmaute** [mariodavid/cuba-component-data-import#159]
Add-On Version: 0.14.0
Platform Version: 7.2.6
Gradle: 5.6.4
Reproduce: Create new project. Add add-on. Run Wizard or create Import Configuration. Try set a Custom Attribute Binding Script in Attribute Mappers.

Error thrown:
```
GuiDevelopmentException: Property 'isColumnRequired' is not found in entity 'ddcdi$ImportAttributeMapper'

Frame ID: ddcdi$ImportAttributeMapperCustom.frame
XML descriptor: de/diedavids/cuba/dataimport/web/importattributemapper/import-attribute-mapper-custom-frame.xml
```

Stacktrace:
```
com.haulmont.cuba.gui.GuiDevelopmentException: Property 'isColumnRequired' is not found in entity 'ddcdi$ImportAttributeMapper', frameId=ddcdi$ImportAttributeMapperCustom.frame
	at com.haulmont.cuba.gui.xml.layout.loaders.FieldGroupLoader.loadField(FieldGroupLoader.java:415)
	at com.haulmont.cuba.gui.xml.layout.loaders.FieldGroupLoader.loadFields(FieldGroupLoader.java:289)
	at com.haulmont.cuba.gui.xml.layout.loaders.FieldGroupLoader.loadFields(FieldGroupLoader.java:279)
	at com.haulmont.cuba.gui.xml.layout.loaders.FieldGroupLoader.loadComponent(FieldGroupLoader.java:140)
	at com.haulmont.cuba.gui.xml.layout.loaders.ContainerLoader.loadSubComponents(ContainerLoader.java:38)
	at com.haulmont.cuba.gui.xml.layout.loaders.ContainerLoader.loadSubComponentsAndExpand(ContainerLoader.java:76)
	at com.haulmont.cuba.gui.xml.layout.loaders.FragmentLoader.loadComponent(FragmentLoader.java:120)
	at com.haulmont.cuba.web.sys.WebFragments.createFragment(WebFragments.java:180)
	at com.haulmont.cuba.web.sys.WebFragments.create(WebFragments.java:94)
	at com.haulmont.cuba.gui.Fragments.create(Fragments.java:55)
	at com.haulmont.cuba.web.sys.WebScreens.openFrame(WebScreens.java:1269)
	at com.haulmont.cuba.web.sys.WebScreens.openFrame(WebScreens.java:1255)
	at com.haulmont.cuba.web.sys.WebScreens.openFrame(WebScreens.java:1249)
	at com.haulmont.cuba.gui.components.HasWindowManager.openFrame(HasWindowManager.java:277)
	at com.haulmont.cuba.gui.components.HasWindowManager$openFrame$0.callCurrent(Unknown Source)
	at de.diedavids.cuba.dataimport.web.importattributemapper.ImportAttributeMapperEdit.postInit(ImportAttributeMapperEdit.groovy:20)
	at com.haulmont.cuba.gui.components.AbstractEditor.setItem(AbstractEditor.java:160)
	at com.haulmont.cuba.gui.components.AbstractEditor.setEntityToEdit(AbstractEditor.java:451)
	at com.haulmont.cuba.web.sys.WebScreens.openEditor(WebScreens.java:1209)
	at com.haulmont.cuba.gui.components.HasWindowManager.openEditor(HasWindowManager.java:119)
	at com.haulmont.cuba.gui.components.HasWindowManager$openEditor.callCurrent(Unknown Source)
	at de.diedavids.cuba.dataimport.web.importwizard.ImportWizard.openAttributeMapperEditor(ImportWizard.groovy:306)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:190)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:58)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:168)
	at de.diedavids.cuba.dataimport.web.importwizard.ImportWizard.newCustomAttributeMapper(ImportWizard.groovy:295)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.haulmont.cuba.gui.xml.DeclarativeAction.actionPerform(DeclarativeAction.java:101)
	at com.haulmont.cuba.web.gui.components.WebPopupButton.lambda$setPopupButtonAction$1(WebPopupButton.java:328)
	at com.haulmont.cuba.web.widgets.CubaButton.fireClick(CubaButton.java:76)
	at com.vaadin.ui.Button$1.click(Button.java:57)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:153)
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:115)
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocation(ServerRpcHandler.java:431)
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:396)
	at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:260)
	at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:82)
	at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40)
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1578)
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:425)
	at com.haulmont.cuba.web.sys.CubaApplicationServlet.serviceAppRequest(CubaApplicationServlet.java:329)
	at com.haulmont.cuba.web.sys.CubaApplicationServlet.service(CubaApplicationServlet.java:215)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:108)
	at org.springframework.web.filter.CompositeFilter.doFilter(CompositeFilter.java:74)
	at com.haulmont.cuba.web.sys.CubaHttpFilter.doFilter(CubaHttpFilter.java:93)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:526)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:678)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:861)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1579)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by mariodavid** [comment]
Hi,

thanks for the info. This is fixed in 0.14.1.

Cheers
Mario
