### ISSUE TITLE
Error when exporting

### ISSUE THREAD

**Issue by innovaringenieria** [mariodavid/cuba-component-data-import#84]
I have noticed that once the component is added, the standard process of Cuba for export stops working. From what I see the entire POI library is updated (3.16 to 3.17) less poi-scratchpad.
Do you know something about it?

![image](https://user-images.githubusercontent.com/22368175/40307526-79767018-5cc8-11e8-9ac8-1737d3217ed5.png)
`java.lang.NoSuchMethodError: org.apache.poi.hssf.usermodel.HSSFFont.getBoldweight()S
	at com.haulmont.cuba.gui.export.ExcelAutoColumnSizer.getFontMetrics(ExcelAutoColumnSizer.java:56)
	at com.haulmont.cuba.gui.export.ExcelAutoColumnSizer.notifyCellValue(ExcelAutoColumnSizer.java:102)
	at com.haulmont.cuba.gui.export.ExcelExporter.exportTable(ExcelExporter.java:196)
	at com.haulmont.cuba.gui.components.actions.ExcelAction.export(ExcelAction.java:217)
	at com.haulmont.cuba.gui.components.actions.ExcelAction.actionPerform(ExcelAction.java:179)`

**Comment by innovaringenieria** [comment]
This bug was [reported](https://www.cuba-platform.com/discuss/t/excel-action-causing-error/5078/5) in the CUBA forum, it's a problem with the POI library.
